### ISSUE TITLE
Feature: Add "limit" condition

### ISSUE THREAD

**Issue by medokin** [deepstreamIO/deepstream.io-provider-search-rethinkdb#1]
I'd like to limit my results. Implementation should be possible without breaking something, right?

See: http://rethinkdb.com/api/javascript/limit/

**Comment by WolframHempel** [comment]
I agree, adding a limit condition would be simple and would speed queries up. Temporarily though, retrieving a longer list and just not subscribing to its records shouldn't come with too much of an overhead.

**Comment by Iiridayn** [comment]
Would probably be most useful paired with https://www.rethinkdb.com/api/javascript/order_by/, which might be a little more complicated to implement (more options).

**Comment by Iiridayn** [comment]
Fix in #47
