### ISSUE TITLE
Own record subscription results in non-robust programming style suggestion

### ISSUE THREAD

**Issue by Iiridayn** [deepstreamIO/deepstream.io-provider-search-rethinkdb#24]
https://deepstream.io/tutorials/core/searching-and-querying/ states:

> It's a good idea to delete your queries when you're finished with them. Do this with:
> 
> ```
> colorPriceString.delete()
> ```

This is not a good idea - it requires writing client code which is aware that it's own queries might be deleted at any moment and resubscribing, should another client delete their search. Furthermore, the code is written such that on the last unsubscription, the record is deleted anyway.

The bug here is as documented at https://deepstream.io/tutorials/core/datasync-records/:

> The listen callback with isSubscribed=false is only triggered once the last subscriber has disconnected or discarded the record. _If your active data provider is subscribed to the record_ as well in order to write to it, it counts as a subscriber and the callback won't be invoked. This is a known limitation and will be addressed in future releases that will also introduce load-balancing for listeners, only-one rules etc

emphasis mine.

Until this update is released, it would be best to only hold an instance of the `_list` record while actively updating it, and discarding it immediately afterward.

**Comment by yasserf** [comment]
Hey, 1.1 release should be out 2moro and will allow subscribe false to be called when client discards!

> The listen callback with isSubscribed=false is only triggered once the last subscriber has disconnected or discarded the record. If your active data provider is subscribed to the record as well in order to write to it, it counts as a subscriber and the callback won't be invoked. This is a known limitation and will be addressed in future releases that will also introduce load-balancing for listeners, only-one rules etc

Gone! Woot!

**Comment by yasserf** [comment]
Closing since fixed in 1.1.1

**Comment by layanto** [comment]
Do I still call list.delete() as per the current documentation? Or list.discard() and search provider will automatically delete the list when there are no subscribers left?

**Comment by yasserf** [comment]
List.discard should work best
