### ISSUE TITLE
Query on path properties

### ISSUE THREAD

**Issue by athakral** [deepstreamIO/deepstream.io-provider-search-rethinkdb#44]
Is it possible to query on a path kind of properties 

```
{
  "name":"John",
   "phone": { "areaCode":"571", "state" : "va" }
}
```

query

```
var queryString = JSON.stringify({
    table: 'users',
        query: [
            [ 'phone.areaCode', 'eq', '571' ],
            [ 'phone.state', 'eq', "va" ]
        ]
});
ds.record.getList( 'search?' + queryString );
```

**Comment by athakral** [comment]
Thanks a ton @WolframHempel  for the fix 

So, I tried it and I could see following log outputs. 

```
LEADING_LISTEN | started for R:search?{"table":"users","query":[["last_name","eq","Thakral"]]}
LOCAL_LISTEN | started for R:search?{"table":"users","query":[["last_name","eq","Thakral"]]}
LOCAL_LISTEN | stopped for R:search?{"table":"users","query":[["last_name","eq","Thakral"]]}
LEADING_LISTEN | finished for R:search?{"table":"users","query":[["last_name","eq","Thakral"]]}
S | for R:search?{"table":"users","query":[["last_name","eq","Thakral"]]} by OPEN
```

and I can see rethinkDb has values, I even ran query in the data explorer just to be sure 

``` js
r.db('ramble_on_db').table('users').filter({
    "last_name": "Thakral"
})
```

and I subscribed to whenReady but list is always empty

``` js
userList.whenReady(() => {
            console.log('list found');
            console.log(userList.isEmpty());
            console.log(userList.getEntries());
        });
```

**Comment by yasserf** [comment]
Can you please show the logs from the provider itself?

**Comment by WolframHempel** [comment]
Actually, whenReady just tells you that the list has been loaded from
deepstreams cache. Use .subscribe to get notified as soon as the search
results are ready

**Comment by athakral** [comment]
@yasserf  logs from provider ?? i thought thats what I provided, Can you please help me, in how to get those logs

@WolframHempel  I tried .subscribe  as well. callback that I am passing to subscribe  is never getting invoked. 

If I am not wrong. This should work for existing records not only new records ? 

and as per https://deepstream.io/docs/client-js/datasync-list/  

callback is suppose to invoke when the list content changes 

"A callback function that will be called whenever the content of the list changes". 

But whenReady is to be used when the list is ready to be read.

**Comment by Iiridayn** [comment]
Running into a problem with this - when using `.` as the `splitChar` in the rethink storage provider, most of our search string is treated as a desired table name, which fails (fortunately) due to containing invalid characters. This is not unique to our case - using `/` as the table separator would cause issues with, eg, strings in the JSON containing `/` (though admittedly less common).
